using KotoDibo.Domain.Enums;

namespace KotoDibo.Domain.Entities;

// A direct cash deposit into the household's shared fund, independent of any specific purchase —
// distinct from BazarPurchase (money out for groceries), this is money in.
public class Contribution
{
    public string Id { get; set; } = string.Empty;
    public string HouseholdId { get; set; } = string.Empty;
    public string ContributedByUserId { get; set; } = string.Empty;
    public DateOnly Date { get; set; }
    public decimal Amount { get; set; }
    public string Currency { get; set; } = string.Empty;
    public string? Notes { get; set; }

    // Manual (default): a member deposited cash directly through the Contributions endpoint.
    // AutoFromBazar: generated by BazarPurchaseService because a member paid for a Bazar purchase
    // personally — see BazarPurchase.FundingSource. Auto-generated rows can only be changed by
    // editing/cancelling their source Bazar purchase (enforced in ContributionService).
    public ContributionSourceType SourceType { get; set; } = ContributionSourceType.Manual;

    // Set only when SourceType is AutoFromBazar: the BazarPurchase this row mirrors.
    public string? SourceBazarPurchaseId { get; set; }

    public FinancialEntryStatus Status { get; set; } = FinancialEntryStatus.Active;
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}
